package com.afrithecus.brainbox.api.media

import com.afrithecus.brainbox.api.common.error.invalidArgument
import com.afrithecus.brainbox.api.common.error.notFound
import com.afrithecus.brainbox.api.common.web.PublicUrlBuilder
import com.afrithecus.brainbox.api.media.security.MediaScanAction
import com.afrithecus.brainbox.api.storage.ObjectStorage
import com.afrithecus.brainbox.api.storage.StorageProperties
import org.springframework.beans.factory.annotation.Qualifier
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Service
import org.springframework.web.multipart.MultipartFile
import java.util.UUID

/**
 * Media storage for uploads (CBC projects, homework attachments, class-chat files)
 * through the shared ObjectStorage seam, so media and report bytes can live in one
 * S3-compatible store instead of a single node's disk. Returns an absolute URL
 * built from the current request so clients fetch it directly.
 *
 * Security: the true format is detected from the file's leading bytes and the
 * client-declared multipart content type is never trusted for the stored type or
 * extension, so an HTML/script payload cannot be smuggled in as an image or under a
 * chosen extension. Every upload is size-capped, unknown binary formats fail closed,
 * and the serving controller adds the anti-sniffing headers.
 */
@Service
class MediaService(
    @Qualifier("mediaObjectStorage") private val storage: ObjectStorage,
    private val storageProperties: StorageProperties,
    private val urls: PublicUrlBuilder,
    /** The malware-scan gate; `none` records uploads as unscanned and changes nothing else. */
    private val scanGate: MediaScanGate,
    @Value("\${app.media.max-upload-bytes:26214400}") private val maxUploadBytes: Long,
) {

    /**
     * Stores an upload and returns its absolute URL. Images/videos are always
     * accepted; [allowDocuments] additionally permits PDFs, EPUBs, plain text and
     * audio for class-chat attachments.
     */
    fun store(file: MultipartFile, allowDocuments: Boolean = false): MediaUploadResponsePayload =
        storeChecked(
            file = file,
            maxBytes = maxUploadBytes,
            allowed = { kind -> kind.isImage || kind.isVideo || (allowDocuments && (kind.isDocument || kind.isAudio)) },
        )

    /**
     * Homework submission attachments: 10 MB max, PDF/DOC/DOCX/JPEG/PNG/plain text
     * (docs/ongoing/api_homework_changes.md, attachment guard).
     */
    fun storeHomeworkAttachment(file: MultipartFile): MediaUploadResponsePayload =
        storeChecked(file, MediaPolicies.ATTACHMENT_MAX_BYTES) { it in MediaPolicies.HOMEWORK_ATTACHMENT_KINDS }

    /** Teacher documents: 10 MB max, PDF/EPUB/plain text. */
    fun storeDocument(file: MultipartFile): MediaUploadResponsePayload =
        storeChecked(file, MediaPolicies.ATTACHMENT_MAX_BYTES) { it in MediaPolicies.DOCUMENT_KINDS }

    /**
     * Deletes a stored file by URL or filename; repeat-safe. The filename must match
     * the stored shape the server writes.
     */
    fun delete(urlOrFilename: String) {
        val filename = urlOrFilename.substringAfterLast('/').trim()
        if (!FILENAME_REGEX.matches(filename)) return
        storage.delete(filename)
    }

    /** Stores server-generated bytes (e.g. a rendered report) and returns their URL. */
    fun storeBytes(bytes: ByteArray, filenameRaw: String, contentType: String): MediaUploadResponsePayload {
        val safe = filenameRaw.replace(Regex("[^A-Za-z0-9._-]"), "_").take(80)
        storage.put(safe, bytes, contentType)
        return MediaUploadResponsePayload(url = urls.mediaUrl(safe), mediaType = "FILE")
    }

    /**
     * A direct-download URL for a stored file, or null when the backend streams the
     * bytes itself (local disk). Validates the filename shape first.
     */
    fun presignedDownloadUrl(filenameRaw: String): String? {
        val filename = filenameRaw.trim()
        if (!FILENAME_REGEX.matches(filename)) return null
        return storage.presignGet(filename, storageProperties.presignTtl)
    }

    /**
     * Loads a stored file as its bytes plus the media type implied by the
     * server-chosen extension. The filename is constrained to the stored shape.
     */
    fun load(filenameRaw: String): Pair<ByteArray, String> {
        val filename = filenameRaw.trim()
        if (!FILENAME_REGEX.matches(filename)) throw notFound("Media not found")
        val bytes = storage.get(filename) ?: throw notFound("Media not found")
        return bytes to contentTypeFor(filename)
    }

    /**
     * The shared upload path: size-cap, detect the real format, apply the caller's
     * allow-list, then store under a server-derived name. The extension always comes
     * from the detected format, never from the client filename.
     */
    private fun storeChecked(
        file: MultipartFile,
        maxBytes: Long,
        allowed: (MediaKind) -> Boolean,
    ): MediaUploadResponsePayload {
        if (file.isEmpty) throw invalidArgument("An upload file is required")
        val bytes = file.bytes
        if (bytes.isEmpty()) throw invalidArgument("An upload file is required")
        if (bytes.size.toLong() > maxBytes) {
            throw invalidArgument("File must be " + (maxBytes / MediaPolicies.BYTES_PER_MB) + " MB or smaller")
        }
        val kind = MediaContentTypes.detect(bytes) ?: throw invalidArgument("Unsupported or unrecognised file type")
        if (!allowed(kind)) throw invalidArgument("Unsupported file type")
        // The proxied path scans before storing, so it accepts exactly what the presigned
        // confirm path accepts; with no scanner configured this is a recorded no-op. The
        // object is not stored yet, so a refusal has nothing to quarantine: the bytes are
        // simply never written.
        val filename = UUID.randomUUID().toString() + "." + kind.extension
        val scan = scanGate.inspect(
            uploadId = null,
            storageKey = filename,
            ownerId = null,
            sizeBytes = bytes.size.toLong(),
            contentType = kind.contentType,
        ) { bytes }
        if (!scan.allowed) {
            throw invalidArgument(
                if (scan.status == MediaScanStatus.INFECTED) {
                    "This file was rejected by the malware scan" + scan.detail?.let { ": " + it }.orEmpty()
                } else {
                    "This file could not be scanned and was refused" + scan.detail?.let { ": " + it }.orEmpty()
                }
            )
        }
        storage.put(filename, bytes, kind.contentType)
        val url = urls.mediaUrl(filename)
        return MediaUploadResponsePayload(
            url = url,
            mediaType = when {
                kind.isVideo -> "VIDEO"
                kind.isImage -> "IMAGE"
                else -> "FILE"
            },
        )
    }

    private fun contentTypeFor(filename: String): String {
        val extension = filename.substringAfterLast('.', "").lowercase()
        return MediaKind.entries.firstOrNull { it.extension == extension }?.contentType ?: "application/octet-stream"
    }

    private companion object {
        /** A UUID plus the detected extension; the only filenames the server ever writes. */
        val FILENAME_REGEX = Regex("""^[A-Za-z0-9-]{1,64}\.[A-Za-z0-9]{1,5}$""")
    }
}
