package com.afrithecus.brainbox.api.media

import com.afrithecus.brainbox.api.common.error.invalidArgument
import com.afrithecus.brainbox.api.common.error.notFound
import com.afrithecus.brainbox.api.storage.ObjectStorage
import org.springframework.beans.factory.annotation.Qualifier
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Service
import org.springframework.web.multipart.MultipartFile
import org.springframework.web.servlet.support.ServletUriComponentsBuilder
import java.util.UUID

/**
 * Media storage for uploads (CBC projects, homework attachments, class-chat files)
 * through the shared ObjectStorage seam, so media and report bytes can live in one
 * S3-compatible store instead of a single node's disk. Returns an absolute URL
 * built from the current request so clients fetch it directly.
 *
 * Security: the true format is detected from the file's leading bytes and the
 * client-declared multipart content type is never trusted for the stored type or
 * extension, so an HTML/script payload cannot be smuggled in as an image or under a
 * chosen extension. Every upload is size-capped, unknown binary formats fail closed,
 * and the serving controller adds the anti-sniffing headers.
 */
@Service
class MediaService(
    @Qualifier("mediaObjectStorage") private val storage: ObjectStorage,
    @Value("\${app.media.max-upload-bytes:26214400}") private val maxUploadBytes: Long,
) {

    /**
     * Stores an upload and returns its absolute URL. Images/videos are always
     * accepted; [allowDocuments] additionally permits PDFs, EPUBs, plain text and
     * audio for class-chat attachments.
     */
    fun store(file: MultipartFile, allowDocuments: Boolean = false): MediaUploadResponsePayload =
        storeChecked(
            file = file,
            maxBytes = maxUploadBytes,
            allowed = { kind -> kind.isImage || kind.isVideo || (allowDocuments && (kind.isDocument || kind.isAudio)) },
        )

    /**
     * Homework submission attachments: 10 MB max, PDF/DOC/DOCX/JPEG/PNG/plain text
     * (docs/ongoing/api_homework_changes.md, attachment guard).
     */
    fun storeHomeworkAttachment(file: MultipartFile): MediaUploadResponsePayload =
        storeChecked(file, HOMEWORK_ATTACHMENT_MAX_BYTES) { it in HOMEWORK_ATTACHMENT_KINDS }

    /** Teacher documents: 10 MB max, PDF/EPUB/plain text. */
    fun storeDocument(file: MultipartFile): MediaUploadResponsePayload =
        storeChecked(file, DOCUMENT_MAX_BYTES) { it in DOCUMENT_KINDS }

    /**
     * Deletes a stored file by URL or filename; repeat-safe. The filename must match
     * the stored shape the server writes.
     */
    fun delete(urlOrFilename: String) {
        val filename = urlOrFilename.substringAfterLast('/').trim()
        if (!FILENAME_REGEX.matches(filename)) return
        storage.delete(filename)
    }

    /** Stores server-generated bytes (e.g. a rendered report) and returns their URL. */
    fun storeBytes(bytes: ByteArray, filenameRaw: String, contentType: String): MediaUploadResponsePayload {
        val safe = filenameRaw.replace(Regex("[^A-Za-z0-9._-]"), "_").take(80)
        storage.put(safe, bytes, contentType)
        val url = ServletUriComponentsBuilder.fromCurrentContextPath().path("/media/").path(safe).toUriString()
        return MediaUploadResponsePayload(url = url, mediaType = "FILE")
    }

    /**
     * Loads a stored file as its bytes plus the media type implied by the
     * server-chosen extension. The filename is constrained to the stored shape.
     */
    fun load(filenameRaw: String): Pair<ByteArray, String> {
        val filename = filenameRaw.trim()
        if (!FILENAME_REGEX.matches(filename)) throw notFound("Media not found")
        val bytes = storage.get(filename) ?: throw notFound("Media not found")
        return bytes to contentTypeFor(filename)
    }

    /**
     * The shared upload path: size-cap, detect the real format, apply the caller's
     * allow-list, then store under a server-derived name. The extension always comes
     * from the detected format, never from the client filename.
     */
    private fun storeChecked(
        file: MultipartFile,
        maxBytes: Long,
        allowed: (MediaKind) -> Boolean,
    ): MediaUploadResponsePayload {
        if (file.isEmpty) throw invalidArgument("An upload file is required")
        val bytes = file.bytes
        if (bytes.isEmpty()) throw invalidArgument("An upload file is required")
        if (bytes.size.toLong() > maxBytes) {
            throw invalidArgument("File must be " + (maxBytes / BYTES_PER_MB) + " MB or smaller")
        }
        val kind = MediaContentTypes.detect(bytes) ?: throw invalidArgument("Unsupported or unrecognised file type")
        if (!allowed(kind)) throw invalidArgument("Unsupported file type")
        val filename = UUID.randomUUID().toString() + "." + kind.extension
        storage.put(filename, bytes, kind.contentType)
        val url = ServletUriComponentsBuilder.fromCurrentContextPath().path("/media/").path(filename).toUriString()
        return MediaUploadResponsePayload(
            url = url,
            mediaType = when {
                kind.isVideo -> "VIDEO"
                kind.isImage -> "IMAGE"
                else -> "FILE"
            },
        )
    }

    private fun contentTypeFor(filename: String): String {
        val extension = filename.substringAfterLast('.', "").lowercase()
        return MediaKind.entries.firstOrNull { it.extension == extension }?.contentType ?: "application/octet-stream"
    }

    private companion object {
        const val BYTES_PER_MB = 1024L * 1024L
        const val HOMEWORK_ATTACHMENT_MAX_BYTES = 10L * 1024 * 1024
        const val DOCUMENT_MAX_BYTES = 10L * 1024 * 1024

        val HOMEWORK_ATTACHMENT_KINDS = setOf(
            MediaKind.PDF,
            MediaKind.DOC,
            MediaKind.DOCX,
            MediaKind.TEXT,
            MediaKind.JPEG,
            MediaKind.PNG,
        )
        val DOCUMENT_KINDS = setOf(MediaKind.PDF, MediaKind.EPUB, MediaKind.TEXT)

        /** A UUID plus the detected extension; the only filenames the server ever writes. */
        val FILENAME_REGEX = Regex("""^[A-Za-z0-9-]{1,64}\.[A-Za-z0-9]{1,5}$""")
    }
}
