package com.afrithecus.brainbox.api.traditional.web

import com.afrithecus.brainbox.api.traditional.model.ExamTerm
import com.afrithecus.brainbox.api.traditional.model.TraditionalEditStatus
import com.afrithecus.brainbox.api.traditional.model.TraditionalExamStatus
import com.afrithecus.brainbox.api.traditional.model.TraditionalSubjectType
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.NotEmpty
import jakarta.validation.constraints.NotNull

// ---------------------------------------------------------------------------
// Traditional (paper) exam payloads. Field names mirror the Android models in
// models/traditional/*.kt and models/analytics/*.kt exactly (client wins over
// the prose docs where they differ).
// ---------------------------------------------------------------------------

data class SubjectComponentDto(
    val componentId: String,
    val name: String,
    val maxScore: Int,
    val weight: Double = 1.0,
)

data class SubjectConfigDto(
    val subjectId: String,
    val name: String,
    val maxScore: Int,
    val type: TraditionalSubjectType = TraditionalSubjectType.SINGLE,
    val components: List<SubjectComponentDto>? = null,
    val isOptional: Boolean = false,
)

data class TraditionalExamDto(
    val examId: String,
    val title: String,
    val term: ExamTerm,
    val gradeLevel: String,
    val year: Int,
    val type: String = "TRADITIONAL",
    val status: TraditionalExamStatus,
    val subjects: List<SubjectConfigDto>,
    val maxScore: Int = 100,
    val autoGenerated: Boolean = true,
    val createdAt: Long,
    val finalizedAt: Long? = null,
    val finalizedBy: String? = null,
    val coordinatorRemarks: String? = null,
    val publishedAt: Long? = null,
    val publishedBy: String? = null,
    /** Tenant scope so the client can preserve it across pulls (TE-3). */
    val schoolId: String? = null,
)

data class TraditionalMarkDto(
    val id: String,
    val examId: String,
    val studentId: String,
    val subjectId: String,
    val rawScore: Int,
    val percentage: Double? = null,
    val gradeBand: String? = null,
    val componentScores: Map<String, Int>? = null,
    val confirmedByTeacher: Boolean = false,
    val confirmedAt: Long? = null,
    val enteredAt: Long,
)

data class MarkEntryDto(
    val studentId: String,
    val subjectId: String,
    val rawScore: Int,
    val componentScores: Map<String, Int>? = null,
)

data class ExamConfirmationStatusDto(
    val examId: String,
    val totalTeachers: Int,
    val confirmedCount: Int,
    val pendingTeachers: List<String>,
)

data class GradeCheckSummaryDto(
    val grade: String,
    val totalStudents: Int,
    val completeStudents: Int,
    val partialStudents: Int,
    val missingStudents: Int,
)

data class PreFinalCheckSummaryDto(
    val gradeChecks: List<GradeCheckSummaryDto>,
)

data class GradingBandDto(
    val grade: String,
    val minPercentage: Int,
)

data class OverallGradingBandDto(
    val grade: String,
    val minRawScore: Int,
)

data class GradingConfigDto(
    val bands: List<GradingBandDto> = GradingConfigDefaults.bands(),
    val overallBands: List<OverallGradingBandDto>? = null,
)

/** Default CBC bands shared with the client (models/traditional/TraditionalExamGrading.kt). */
object GradingConfigDefaults {
    fun bands(): List<GradingBandDto> = listOf(
        GradingBandDto("EE", 80),
        GradingBandDto("ME", 65),
        GradingBandDto("AE", 50),
        GradingBandDto("BE", 35),
        GradingBandDto("DE", 20),
        GradingBandDto("E", 0),
    )

    fun overallBands(): List<OverallGradingBandDto> = listOf(
        OverallGradingBandDto("EE", 350),
        OverallGradingBandDto("ME", 280),
        OverallGradingBandDto("AE", 200),
        OverallGradingBandDto("BE", 120),
    )
}

data class EditRequestDto(
    val id: String,
    val examId: String,
    val teacherId: String,
    val studentId: String,
    val subjectId: String,
    val oldScore: Int,
    val newScore: Int,
    val reason: String,
    val status: TraditionalEditStatus = TraditionalEditStatus.PENDING,
    val reviewedBy: String? = null,
    val reviewedAt: Long? = null,
    val coordinatorComment: String? = null,
    val createdAt: Long,
)

data class EditPermissionDto(
    val permissionId: String,
    val examId: String,
    val studentId: String,
    val teacherId: String,
    val grantedBy: String,
    val grantedAt: Long,
    val expiresAt: Long,
    val used: Boolean = false,
)

data class StudentDto(
    val id: String,
    val name: String,
    val className: String,
    val admissionNumber: String,
    val avatarUrl: String? = null,
)

// --------------------------------------------------------------- reports

data class SubjectComponentResultDto(
    val name: String,
    val rawScore: Int,
    val maxScore: Int,
    val percentage: Double,
    val grade: String,
)

data class TraditionalSubjectResultDto(
    val subjectName: String,
    val rawScore: Int,
    val maxScore: Int,
    val percentage: Double,
    val grade: String,
    val isCombined: Boolean = false,
    val componentDetails: String? = null,
    val components: List<SubjectComponentResultDto>? = null,
)

data class TraditionalStudentReportDto(
    val studentId: String,
    val studentName: String,
    val admissionNumber: String,
    val gradeLevel: String,
    val classTag: String,
    val term: String,
    val year: Int,
    val subjectResults: List<TraditionalSubjectResultDto>,
    val totalScore: Int,
    val overallPercentage: Double,
    val overallGrade: String,
    val classPosition: Int,
    val totalStudentsInClass: Int,
    val teacherRemarks: String? = null,
    val schoolName: String,
    val schoolLogo: String? = null,
)

data class TopPerformerDto(
    val studentId: String,
    val studentName: String,
    val totalScore: Int,
    val percentage: Double,
    val rank: Int,
)

data class StrugglingStudentDto(
    val studentId: String,
    val studentName: String,
    val totalScore: Int,
    val percentage: Double,
    val weakSubjects: List<String>,
)

data class TraditionalExamAnalyticsDto(
    val examId: String,
    val examTitle: String,
    val gradeLevel: String,
    val classMean: Double,
    val medianScore: Double,
    val standardDeviation: Double,
    val highestScore: Int,
    val lowestScore: Int,
    val topPerformers: List<TopPerformerDto>,
    val strugglingStudents: List<StrugglingStudentDto>,
    val gradeDistribution: Map<String, Int>,
    val subjectAverages: Map<String, Double>,
    val classComparison: Map<String, Double>? = null,
    val totalStudents: Int,
    val confirmedTeachers: Int,
    val totalTeachers: Int,
)

data class StudentGradeRowDto(
    val rank: Int,
    val studentId: String,
    val studentName: String,
    val classTag: String,
    val subjects: List<TraditionalSubjectResultDto>,
    val totalPercentage: Double,
    val totalScore: Int,
    val overallGrade: String,
)

data class ClassGradeAnalysisDto(
    val classTag: String,
    val teacherName: String,
    val subjectAverages: Map<String, Double>,
    val subjectPositions: Map<String, Int>,
    val totalAverage: Double,
    val overallPosition: Int,
)

data class TraditionalGradeAnalysisDto(
    val examId: String,
    val gradeLevel: String,
    val term: String,
    val year: Int,
    val classes: List<ClassGradeAnalysisDto>,
)

/** Body for POST /traditional/exams (client sends the full TraditionalExam model). */
data class CreateTraditionalExamRequest(
    /** The client's deterministic exam id; stored and echoed so CREATE_EXAM replay is idempotent. */
    val examId: String? = null,
    @field:NotBlank val title: String,
    @field:NotNull val term: ExamTerm,
    @field:NotBlank val gradeLevel: String,
    @field:NotNull val year: Int,
    @field:NotEmpty val subjects: List<SubjectConfigDto>,
    val maxScore: Int = 100,
    val autoGenerated: Boolean = true,
)
