package com.afrithecus.brainbox.api.traditional.entity

import com.afrithecus.brainbox.api.common.jpa.BaseEntity
import com.afrithecus.brainbox.api.traditional.model.ExamTerm
import com.afrithecus.brainbox.api.traditional.model.TraditionalExamStatus
import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.Table
import java.time.Instant
import java.util.UUID

/** A paper-based exam with a coordinator-driven lifecycle (doc 10 §1.2). */
@Entity
@Table(name = "traditional_exams")
class TraditionalExamEntity : BaseEntity() {

    @Column(nullable = false)
    var title: String = ""

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    var term: ExamTerm = ExamTerm.TERM_1

    @Column(name = "grade_level", nullable = false, length = 64)
    var gradeLevel: String = ""

    @Column(name = "exam_year", nullable = false)
    var year: Int = 0

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 32)
    var status: TraditionalExamStatus = TraditionalExamStatus.PENDING

    @Column(name = "max_score", nullable = false)
    var maxScore: Int = 100

    @Column(name = "auto_generated", nullable = false)
    var autoGenerated: Boolean = true

    @Column(name = "school_id")
    var schoolId: UUID? = null

    /**
     * The Android client's deterministic exam id (e.g. TRAD_Grade4_OPENER_2026_T1).
     * The server UUID stays the internal primary key; this column lets every
     * endpoint and payload speak the id the client stores locally.
     */
    @Column(name = "client_exam_id", length = 128)
    var clientExamId: String? = null

    @Column(name = "created_by", nullable = false)
    var createdBy: UUID = UUID.randomUUID()

    @Column(name = "finalized_at")
    var finalizedAt: Instant? = null

    @Column(name = "finalized_by")
    var finalizedBy: UUID? = null

    @Column(name = "coordinator_remarks", columnDefinition = "text")
    var coordinatorRemarks: String? = null

    @Column(name = "published_at")
    var publishedAt: Instant? = null

    @Column(name = "published_by")
    var publishedBy: UUID? = null
}
